# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e709347d5b7575293050de27ca01f857e60e0954e18703ca1857a8f5b4d07420bdf2545126e84c79ef7360a5384542ce868839ffd2d793ed26019cef6f52a1dd

test:
  secret_key_base: d0b742277714d118850675506f9658ca65041ebec9d5652359c4b7948be3a4786256a7ef2fffaf2ae4890b75f7d43ee1069656ffaadfa71f46b8bc74f9fd1a13

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
